### ISSUE TITLE
Can the two boards in the example communicate with each other?

### ISSUE THREAD

**Issue by Heath68** [named-data-iot/ndn-iot-package-over-nordic-sdk#1]
Hello，the two nRF52840 LED light switches can be controlled by android. Can the two boards communicate via ndn-lite?

**Comment by peurpdapeurp** [comment]
Hello,

At least in the BLE example, the two boards should be able to communicate if you press one of the buttons after onboarding (they should be able to cause one of the LED's on the other board to blink).

Within the next few weeks the examples will be updated to give more clear instructions.

**Comment by Heath68** [comment]
Tank you!So two boards communicate with each other via BLE instead of 802.15.4 in the BLE example.But in the 802.14.5 example, the two boards communicate with each other via 802.15.4,right?

**Comment by peurpdapeurp** [comment]
Ah yes, that is correct.
