### ISSUE TITLE
Redo the Android Example

### ISSUE THREAD

**Issue by peurpdapeurp** [named-data-iot/ndn-iot-package-over-nordic-sdk#12]
The current Android example is confusing. I will rewrite it to have a simpler UI that makes it more obvious what is actually happening.

**Comment by Paul-HIT** [comment]
I compiled and installed the BLE-example on Nordic board, I also installed the Android APP on the phone, but there's no response from the board when I press any button on the phone or on the board.

**Comment by Paul-HIT** [comment]
> The current Android example is confusing. I will rewrite it to have a simpler UI that makes it more obvious what is actually happening.
I compiled and installed the BLE-example on Nordic board, I also installed the Android APP on the phone, but there's no response from the board when I press any button on the phone or on the board.

**Comment by paulyu12** [comment]
I compiled and installed the BLE-example on Nordic board, I also installed the Android APP on the phone, but there's no response from the board when I press any button on the phone or on the board.

**Comment by peurpdapeurp** [comment]
I am currently rewriting the Android example in response to this issue: https://github.com/named-data-iot/ndn-iot-package-over-nordic-sdk/issues/19

I should be done around the end of this week; I think the Android app should be easier for you to get working then.

If you need to get things done sooner, you might find this alternate example helpful (it is essentially what I am going to redo the current example into): https://github.com/peurpdapeurp/ndn-lite-android-support-library

**Comment by paulyu12** [comment]
Thanks for your reply.

**Comment by peurpdapeurp** [comment]
The Android example has been updated to be far simpler. The UI is now just a log, which will give you more detailed messages regarding the sign-on protocol.
