### ISSUE TITLE
There is no main_board2.c in new version of BLE example

### ISSUE THREAD

**Issue by Heath68** [named-data-iot/ndn-iot-package-over-nordic-sdk#14]
Since there is no main_board2 ,I debuged same project on the board,but they cannot communicate with each other,when I pressed button3,LED1 on the other board would not blink.

**Comment by peurpdapeurp** [comment]
This is by design. You can switch between board 1 and board 2 by commenting out #define BOARD_1 and uncommenting out #define BOARD_2 in sign-on-basic-credentials.h; this will be better documented after I finish fixing the examples.
