### ISSUE TITLE
How to define a new app_timer?

### ISSUE THREAD

**Issue by Heath68** [named-data-iot/ndn-iot-package-over-nordic-sdk#16]
I wrote the timer code to get temperature data with app_timer,which runs well,but I am afraid of two app_timers conflicting with each other,is it right to change the parameter of app_timer instance initialization(APP_TIMER_DEF(m_repeated_timer_id)---->APP_TIMER_DEF(my_timer_id))?

**Comment by peurpdapeurp** [comment]
I don't believe this is an issue.

Unless I have a misunderstanding, the APP_TIMER_DEF API will allow you to create separate application timers and give them separate ID's. So if you use the APP_TIMER_DEF in your main application, as long as it has a different name from the APP_TIMER_DEF used in the ndn-lite library's implementation, it should be fine.

This is why the nRF SDK's API's for starting and stopping timers take an application timer ID as an argument; they allow for multiple simultaneous application timers that are all over the same RTC (RTC1 I believe). 

That being said, it may cause issues if you create too many app timers; that may interfere with the ndn-lite library's ability to accurately keep track of time. However, that is an issue that we will address later.
