### ISSUE TITLE
Something wrong with sign-on protocol between android and boards

### ISSUE THREAD

**Issue by Heath68** [named-data-iot/ndn-iot-package-over-nordic-sdk#17]
I downloaded the new version of the BLE example, and it can run well.But still cannot sign on the Android,when I press the "show signed on device"button,there is no reaction at all.Still waiting for your new version of NDN-IoT-Android to figure out if it is because of incompatibility.

**Comment by Paul-HIT** [comment]
Hello, 

Have you @Heath68  solve the problem and how ?  I installed the examples on boards rightly but the installed Andoird app never works.

**Comment by Heath68** [comment]
I've solved this issue.The reason boards couldn't sign on Android is that I didn't open all permissions of
 APP.

**Comment by paulyu12** [comment]
How shoud I operate on App? Need I press button of bootstrap first ? What's the steps, please ?

**Comment by paulyu12** [comment]
There's no reaction after I press "Show signed on device". Is it something wrong?

**Comment by paulyu12** [comment]
I have opened all premissions but it's still not working. Besides I have some confusions and I'll appreciate it if we can chat with wechat (My ID: yupeng9437). @Heath68

**Comment by peurpdapeurp** [comment]
The Android example has been updated to be simpler. If you try to use the newest Android example with the boards, it may help in making it clearer why the sign-on protocol is not working between the Android phone and the boards.

**Comment by Heath68** [comment]
Once you turn on the boards,boards will sign on the Android by themselves,and the LED3 on boards will blink.Then you can press show sign-on devices button,the boards signed on will be shown.

**Comment by paulyu12** [comment]
Thank you all. I have downloaded the newest version of the Android app and have a try.

**Comment by peurpdapeurp** [comment]
As was discovered in issue https://github.com/named-data-iot/ndn-iot-package-over-nordic-sdk/issues/23, the issues Paul-HIT were having were due to board incompatibility. A more general issue will be created to get the ndn-lite library to support more models of nRF board besides the nRF52840.
