### ISSUE TITLE
What is the specific function of bootstrapping?

### ISSUE THREAD

**Issue by Heath68** [named-data-iot/ndn-iot-package-over-nordic-sdk#18]
I looked at the code carefully and realized there is a bootstrap function defined in Android but no any reaction function in boards,is it because this function is not being implemented?

**Comment by peurpdapeurp** [comment]
The security bootstrapping is a 2 round trip message exchange between the boards and Android phone. All of the necessary code for the exchange is on both Android and the boards.

You can look at the board's code for sign-on here: https://github.com/named-data-iot/ndn-iot-package-over-nordic-sdk/blob/master/adaptation/app-support-adaptation/secure-sign-on-nrf-sdk-ble/sign-on-basic-client-nrf-sdk-ble.h
