### ISSUE TITLE
When I cloned provided ndn-lite repository ,there is no adaptation folder.

### ISSUE THREAD

**Issue by Heath68** [named-data-iot/ndn-iot-package-over-nordic-sdk#2]
There are some differences between ndn-lite you provided and the original one(https://github.com/named-data-iot/ndn-lite).When I build the BLE example,there are lots of errors about file existence,can you tell me the solution to fix it?

**Comment by peurpdapeurp** [comment]
Hello, apologies for the late response; I was caught up in finals for classes.

We are currently refactoring the platform specific parts of ndn-lite, which included removing the adaptation folder from the main repository; it will be added back to this repository by the end of the day.

**Comment by peurpdapeurp** [comment]
Hello, apologies for the late response; I was caught up in finals for classes.

We are currently refactoring the platform specific parts of ndn-lite, which included removing the adaptation folder from the main repository; it will be added back to this repository by the end of the day.

**Comment by peurpdapeurp** [comment]
Apologies, the refactoring is still not done; I will try to finish it by the end of tomorrow (I think this is more likely to happen).

**Comment by peurpdapeurp** [comment]
The adaptation folder has been added; however, the example will have to be modified to reflect the latest version of the ndn-lite library; this should be done within the next few days.

**Comment by Heath68** [comment]
Ok,thank you so much.Another question:the former example can be deployed as usual?

**Comment by peurpdapeurp** [comment]
I think it is unlikely; both of these examples were written based on an older version of the ndn-lite library, so they will likely not even compile with the latest version.

Unfortunately you will probably have to wait until I have updated both of the examples to be compatible with the latest version of ndn-lite before you start using them again; I will start with the BLE example first and then move to the 802.15.4 example. This should be done within the next few days, and I will keep you updated here.

**Comment by peurpdapeurp** [comment]
Just thought I should make a comment here; we will likely be removing this repository, as it is too similar to the other repository (https://github.com/named-data-iot/ndn-iot-package-over-nordic-sdk-gcc)

I will be trying to modify the examples to use the ndn-iot-package-over-nordic-sdk-gcc repository, I will update this issue when that is done as well

**Comment by peurpdapeurp** [comment]
Just thought I should post an update here; the ndn-iot-package-over-nordic-sdk-gcc repo (https://github.com/named-data-iot/ndn-iot-package-over-nordic-sdk-gcc) has actually been merged into this repo; eventually all of the examples in this repo will have the option of being built with either a gcc toolchain or the Segger Embedded Studio IDE

In addition, the BLE example has been updated to compile with the latest version of ndn-lite at this point; the next step is to test that it still works, and make any adjustments as necessary. After that the 802.15.4 example will be addressed.

**Comment by peurpdapeurp** [comment]
I will close this issue since it was initially an issue related to no adaptation folder; the adaptation folder has now been added and is compilable, so this issue has been resolved.

I will create another issue related to the actual usability of the examples for example related updates.
