### ISSUE TITLE
 Error occurs when I build ndn-lite-application-for-nRF52840-802154 example.

### ISSUE THREAD

**Issue by paulyu12** [named-data-iot/ndn-iot-package-over-nordic-sdk#21]
...
  Compiling ‘nrf_sdh_ble.c’
  Compiling ‘nrf_sdh_soc.c’
  Compiling ‘sign-on-basic-tlv-helpers.c’
    LOCAL_PATH\ndn-lite\app-support\bootstrapping\secure-sign-on-files\secure-sign-on\tlv\sign-on-basic-tlv-helpers.c: No such file or directory
Build failed

I have checked ndn-lite repo, there's indeed no file named sign-on-basic-tlv-helpers.c

**Comment by peurpdapeurp** [comment]
The 802154 example still needs to be updated. I will work on the that after I have resolved the main issues with the BLE example.

**Comment by peurpdapeurp** [comment]
Since there is already an issue to fix the 802.15.4 example (https://github.com/named-data-iot/ndn-iot-package-over-nordic-sdk/issues/10), I will close this issue to reduce the number of redundant issues.
