### ISSUE TITLE
The Android app cannot connect to the boards via BLE

### ISSUE THREAD

**Issue by paulyu12** [named-data-iot/ndn-iot-package-over-nordic-sdk#22]
With program having been written to the board, I run the android app on the device with Android Studio.

I have open all the permissions of the app. 

Error reports is shown in the snapshot below. I am sorry that I don't have the experience about android developing, so the error is probably a simple issue. 
![1](https://user-images.githubusercontent.com/14888724/56630121-afa33080-6682-11e9-9032-1261f114d2fb.PNG)
![2](https://user-images.githubusercontent.com/14888724/56630122-b03bc700-6682-11e9-8152-97c6ee83b556.PNG)
![errors](https://user-images.githubusercontent.com/14888724/56630123-b03bc700-6682-11e9-9cb7-1f27ec38e762.PNG)

**Comment by peurpdapeurp** [comment]
I feel that this may be an issue with the Android phone that you are using; nothing looks particularly wrong with the log that you have shown me.

What model of Android phone are you testing on? I have been doing my testing on the Google Pixel 2 and it works.

**Comment by paulyu12** [comment]
I do the testing on Chinese production, Huawei mate 20 (android 9, bluetooth 5.0) and Mi 8 (android 8, bluetooth 5.0).  The result is the same. 

When you scan directly with the bluetooth tool on the phone, can you find the board on the phone? Why I can not ?

**Comment by peurpdapeurp** [comment]
I can also find the nRF52840 board using a bluetooth tool on my phone. If you cannot find your board using an external bluetooth tool, then it likely won't work with the NDN-IoT application either. I will try seeing if I can add more debugging to the Android application to help with this.

**Comment by paulyu12** [comment]
Thanks for that.

What's the name of the board in your phone's bluetooth scanned list, like this: 77:F3:E9:D1:11:A8 ? I am not sure it is the name of the board in my environment.

**Comment by peurpdapeurp** [comment]
77:F3:E9:D1:11:A8, and anything that looks like it, are the MAC address of the Bluetooth device. The actual name of your board (which is given through the BLE protocol) will be an actual ASCII string, like "Nordic Board" or something similar. A board MUST have a MAC address, but it may or may not have a BLE name (if it does not have a name, you will likely just see "null" in the BLE scanning app you are using).

**Comment by paulyu12** [comment]
ops... There are only MAC addresses. There's no ASCII string name or "null" in my phone's bluetooth scanned list, But I do have written the example program onto the board.

**Comment by paulyu12** [comment]
But when I copy the hex of "BLE Peripheral Template" example (provided by nRF52 sdk) onto the board, The board ascii string name can be found as "Nordic Board template" in my phone's bluetooth tool

**Comment by peurpdapeurp** [comment]
Ah I see; I am quite sure that should be by design (the BLE configuration of the ndn-lite adaptation of nrf SDK BLE does not use the BLE name field, since it is a waste of bytes with respect to what ndn-lite uses BLE for).

I will look into this more in the coming days.

**Comment by paulyu12** [comment]
Can I copy the generated .hex and .elf files directly onto the board via USB ? I found the last two steps of "SES build and run" is that downloading s140_nrf52_6.1.0_softdevice.hex and ndn_lite_nRF52840_example.elf to J-Link. 
![download](https://user-images.githubusercontent.com/14888724/56705252-cf9a2900-6742-11e9-845b-2ce999ccaa4a.PNG)

**Comment by peurpdapeurp** [comment]
I am quite sure that you can do that; I typically just use Segger Embedded studio for uploading software to the board, which does use J-link.

**Comment by peurpdapeurp** [comment]
It turns out that this was because of board incompatibility; the user was trying to use a pca10040 Nordic board (nRF52 DK) instead of the pca10056 Nordic board (nRF52840).

This issue will be replaced by a more general issue to get the ndn-lite library to support more models of nRF boards.
