### ISSUE TITLE
How to run the example on pca10040 board ?

### ISSUE THREAD

**Issue by paulyu12** [named-data-iot/ndn-iot-package-over-nordic-sdk#23]
I found that my board is pca10040, whose pins is not same as pca10056. How can I modify the project for running the ble example? Only to edit the file nrf-sdk-led.h (change  #include "pca10056.h" to #include "pca10040.h") is OK ?

![led](https://user-images.githubusercontent.com/14888724/56707678-67504500-674c-11e9-80a9-a244d2ce28c5.png)
![IMG_20190425_112116](https://user-images.githubusercontent.com/14888724/56707730-9ebef180-674c-11e9-9a51-d1494dbd6f54.jpg)

**Comment by peurpdapeurp** [comment]
I am not entirely sure how to resolve this at the moment; I will try looking into how BLE is supported for pca10040 as opposed to pca10056.

Just wondering, is the board you have the nRF52840?

**Comment by paulyu12** [comment]
OMG, thanks a lot for your patient instruction. The reason of the errors is that I... bought wrong boards !!!

I bought the nRF52 DK, not nRF52840 DK. They are too similar for me -- a novice of embeded development. We simulated ndn tests only with ndnSIM before.

**Comment by peurpdapeurp** [comment]
Ah I see.

I still think it is good that you brought up the fact that our code does not work on different models of the nRF boards; this is something that we will probably have to try to account for in the future, to ensure that ndn-lite can work on all different nRF boards besides just the nRF52840.

I will close this issue and create a more general issue for getting the ndn-lite library to work with different models of Nordic boards (https://github.com/named-data-iot/ndn-iot-package-over-nordic-sdk/issues/24).
