### ISSUE TITLE
What is the function of ndn_forwarder_receive?

### ISSUE THREAD

**Issue by Heath68** [named-data-iot/ndn-iot-package-over-nordic-sdk#25]
Hello,
I found ndn_forwarder_receive() function in forwarder API:https://github.com/named-data-iot/ndn-lite/blob/58a96e73293d488899c9cfc82caaba490705d792/forwarder/forwarder.c ,but don't know what does it work.Can you tell me ?

**Comment by tianyuan129** [comment]
`ndn_forwarder_receive()` doesn't need to be called by application, when network face (e.g., nRF BLE) receives a packet and decides to forward it to the forwarder, this function will be called automatically. See the [nRF BLE face](https://github.com/named-data-iot/ndn-iot-package-over-nordic-sdk/blob/master/adaptation/face/ndn-nrf-ble-face.c). Same design is also the in the [802.15.4 face](https://github.com/named-data-iot/ndn-iot-package-over-nordic-sdk/blob/master/adaptation/face/ndn-nrf-802154-face.c). `ndn_face_receive()` is the old version of `ndn_forwarder_receive()`. But this face is a bit outdated and not compatible with current NDN-Lite.
