### ISSUE TITLE
How to get parameter of an interest on Android?

### ISSUE THREAD

**Issue by Heath68** [named-data-iot/ndn-iot-package-over-nordic-sdk#26]
If board send Android an interest with parameter,how to get the parameter on the Android?Is lpPacket_ represent parameter？

**Comment by peurpdapeurp** [comment]
You should use the getApplicationParameters function, which is in this file of the jndn library: https://github.com/named-data/jndn/blob/master/src/net/named_data/jndn/Interest.java
