### ISSUE TITLE
Is KSpub and BOOTSTRAP_ECC_PUBLIC_NO_POINT_INDENTIFIER the same ?

### ISSUE THREAD

**Issue by paulyu12** [named-data-iot/ndn-iot-package-over-nordic-sdk#27]
1. Is KSpub and BOOTSTRAP_ECC_PUBLIC_NO_POINT_IDENTIFIER the same ?
https://github.com/gujianxiao/NDN-IoT-Android/blob/7c88f74cf903330174961e339444b87a7bd1dc65/ndn_lite_support_library/src/main/java/NDNLiteSupport/SignOnBasicControllerBLE/secureSignOn/secureSignOnVariants/basic/SignOnBasicController.java#L122
https://github.com/gujianxiao/NDN-IoT-Android/blob/7c88f74cf903330174961e339444b87a7bd1dc65/app/src/main/java/com/example/HARDCODED_EXPERIMENTATION_SIGN_ON_BLE_ECC_256.java#L24

2. Why does BOOTSTRAP_ECC_PUBLIC_NO_POINT_IDENTIFIER have 64 byte, while BOOTSTRAP_ECC_PRIVATE only have 32 bytes ? Do they belong to the same keypair ?
https://github.com/gujianxiao/ndn-lite-application-for-nRF52840-BLE_version/blob/1fb3323b3cbf8f34c5d975e5c63b120914aab2f2/Application/ndn-sign-on/sign-on-basic-credentials.c#L31
https://github.com/gujianxiao/ndn-lite-application-for-nRF52840-BLE_version/blob/1fb3323b3cbf8f34c5d975e5c63b120914aab2f2/Application/ndn-sign-on/sign-on-basic-credentials.c#L38

**Comment by peurpdapeurp** [comment]
1. Yes. KSpub is the public key of the KS key pair, and BOOTSTRAP_ECC_PUBLIC_NO_POINT_IDENTIFIER is a buffer that contains the bytes of the public key of the KS key pair.

2.  The KS key pair is an ECC 256 key pair. In elliptic curve cryptography, the public and private keys are different sizes; typically the public key is twice the size of the private key.
