### ISSUE TITLE
ndn-lite/encode/decoder.c: No such file or directory

### ISSUE THREAD

**Issue by Heath68** [named-data-iot/ndn-iot-package-over-nordic-sdk#3]
SES remind me this error when I build BLE example,and I checked ndn-lite folder,there is no decoder.c & encoder.c indeed.Could you tel me how to solve this problem?

**Comment by peurpdapeurp** [comment]
Apologies, I am not entirely sure how to resolve this issue. However, I am going to be working on cleaning up and getting this repository functional today, so I will let you know if I run into the same issue and will let you know how to resolve it if I do.

**Comment by peurpdapeurp** [comment]
This will not be an issue anymore (at least with the BLE example); this was likely because the older versions of the examples included these files as source files from an older version of ndn-lite, but they have been removed in newer versions of ndn-lite.

**Comment by peurpdapeurp** [comment]
I will fix the 802.15.4 example to address this issue after finishing fixing the BLE example.
