### ISSUE TITLE
Can this BLE example only be used in LAN? Can we communicate with nRF52840 boards via ndn-lite by devices beyond LAN?

### ISSUE THREAD

**Issue by Heath68** [named-data-iot/ndn-iot-package-over-nordic-sdk#5]
The communicate distance of BLE is quite short,we want to implement remote access of the data,can NDN-lite be applied in Raspberry Pi?If not,do you have any ideas about remote access?

**Comment by peurpdapeurp** [comment]
Ah, if you would like to send data over longer distances, for now you will have to use TCP or UDP tunnels; that is what is done in the NDN testbed (https://named-data.net/ndn-testbed).

If you would like to use ndn-lite on the Raspberry Pi, you can visit this repository: https://github.com/named-data-iot/ndn-iot-package-over-posix

You can theoretically communicate with nRF52840 boards over any distance you please; the ndn-lite library provides functionality to encode and decode interest / data packets, so as long as this data can be delivered from board to board, then you can use the ndn-lite library to encode / decode and process this data.
