### ISSUE TITLE
Implement ndn-lite's uniform-time APIs using nRF timers

### ISSUE THREAD

**Issue by peurpdapeurp** [named-data-iot/ndn-iot-package-over-nordic-sdk#6]
This is the current block of all other issues; I have been researching how to use the nRF timers to implement a constantly running system clock, in order to be able to get the time in ms or us since startup.

The main problem seems to be that many of the hardware timers don't have many bits, or they are taken to be used exclusively by the softdevice (https://devzone.nordicsemi.com/tutorials/b/software-development-kit/posts/application-timer-tutorial).

Another issue is that even if I implement the timer using an application timer, which they do provide an easy to use API for, the issue is that it stops users from using this application timer. In addition, I do not currently know of any way to completely stop users from using this application timer, so it may cause issues if they use it in their application without realizing that it is used as the timer for ndn-lite as well.

Currently looking into this issue more.

**Comment by peurpdapeurp** [comment]
This seems promising (https://devzone.nordicsemi.com/f/nordic-q-a/29013/best-way-to-implement-system-clock-on-nrf51), looking into this...

**Comment by peurpdapeurp** [comment]
Currently looking at this: https://github.com/NordicPlayground/nrf5-calendar-example

**Comment by peurpdapeurp** [comment]
It seems to be emphasized by this post I've found (https://devzone.nordicsemi.com/f/nordic-q-a/2105/how-to-deal-with-a-long-time-s-clock-drift) that there is an issue with just using the app_timer. It seems that there are only two real time clocks on board of the nRF52840, with one being used by the soft device and the other being the app timer. So if ndn-lite takes the RTC used by the app timer to implement its API's, then the users will not be able to use a timer in their applications, which seems unacceptable. I will keep trying to look into ways to get around this.

**Comment by peurpdapeurp** [comment]
Have found this, this seems interesting: https://devzone.nordicsemi.com/f/nordic-q-a/14982/rtc0-nrf-52-read-counter-value

**Comment by peurpdapeurp** [comment]
Thought I should just leave this link here; it offers some explanation as to why we can't just use the same RTC as the softdevice (RTC0): https://devzone.nordicsemi.com/f/nordic-q-a/5235/usage-of-rtc0-as-time-basis-system-time-possible

**Comment by peurpdapeurp** [comment]
I just noticed from reading the post regarding using rtc 0 as a system time basis that it seems that there are actually more RTC's than just RTC0 and RTC1... so maybe the RTC's other than RTC0 are a software abstraction of a single hardware timer? That might make it okay to have ndn-lite use RTC1 and just tell users that they can't use it.. looking into the timer library to get a better idea of this now (https://www.nordicsemi.com/DocLib/Content/SDK_Doc/nRF5_SDK/v15-2-0/lib_timer)

**Comment by peurpdapeurp** [comment]
Ah so it turns out that the "app timer" deals exclusively with RTC1, I'm now looking in to how to use RTC2 here (https://devzone.nordicsemi.com/f/nordic-q-a/22941/how-to-enable-and-use-rtc0-rtc1-and-rtc2----nrf52832)

**Comment by peurpdapeurp** [comment]
Another thing that makes things a little more complicated that I've just realized after reading this post (https://devzone.nordicsemi.com/f/nordic-q-a/17335/how-many-rtc-use-inside-ble_uart-example-of-sdk-12) is that different nRF board models have different numbers of RTC's; it seems that some models of the board like the nRF51422 only has two RTC's; so the main issue now seems to be whether you can have multiple instances of timers based on the same hardware RTC. I am pretty sure I've seen a post implying that this is possible, will look into this more.

**Comment by peurpdapeurp** [comment]
Ah so this post makes it seems very clear that you can actually have multiple timer instances on top of the same hardware; this means that there is really no problem with ndn-lite using RTC1. https://devzone.nordicsemi.com/f/nordic-q-a/24177/question-on-multiple-channels-in-timers-in-nrf52

I will now just work on figuring out how to do this, just to make sure for myself that this is indeed the case.

**Comment by peurpdapeurp** [comment]
Since we are merging code from the ndn-lite-over-nordic-sdk-gcc repo (https://github.com/named-data-iot/ndn-iot-package-over-nordic-sdk-gcc), this is no longer an issue; I will use the implementation of this from that repo.

**Comment by Heath68** [comment]
I want to implement temperature collection,so I have to use timer to get the temperature data every 500ms.Does this problem you mentioned have influence on my case？

**Comment by Heath68** [comment]
Can I get your E-mail address and contact you ?I`ve got a lot of questions about your contribution.

**Comment by peurpdapeurp** [comment]
Hello; this should not causetoo many issues now, but you may have to work around the current ndn-lite timer implementation since it uses the app_timer library. If you would like to email me with your issues, you can do so at edwardzlu98@gmail.com, but it would be better to raise your issues here so that it can be public and help others in the future.

**Comment by peurpdapeurp** [comment]
To be more specific, the current ndn-lite timer implementation uses the app_timer library; I have to check whether this library allows for the creation of multiple timers before giving you a more definite answer. I will do that now.

**Comment by peurpdapeurp** [comment]
I have confirmed that you can make multiple app timers using the nrf SDK's app_timer library. THE CAVEAT IS THAT YOU MUST NOT RE-INITIALIZE THE APP_TIMER LIBRARY. (i.e., do not call app_timer_init() again; this will erase information about the ndn-lite app-timer, and stop the ndn-lite's system time from functioning correctly). I will make a note of this in the README of this repository.
